export const UserRoleEnum = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  USER: 'user',
};

export const ALL_TAGS = [
  { name: 'arrays', cat: 'data structures' },
  { name: 'strings', cat: 'data structures' },
  { name: 'linked-list', cat: 'data structures' },
  { name: 'stack', cat: 'data structures' },
  { name: 'queue', cat: 'data structures' },
  { name: 'hash-map', cat: 'data structures' },
  { name: 'trees', cat: 'data structures' },
  { name: 'binary-tree', cat: 'data structures' },
  { name: 'graph', cat: 'data structures' },
  { name: 'dynamic-programming', cat: 'algorithms' },
  { name: 'recursion', cat: 'algorithms' },
  { name: 'sorting', cat: 'algorithms' },
  { name: 'binary-search', cat: 'algorithms' },
  { name: 'two-pointers', cat: 'algorithms' },
  { name: 'greedy', cat: 'algorithms' },
  { name: 'backtracking', cat: 'algorithms' },
  { name: 'memoization', cat: 'algorithms' },
  { name: 'time-complexity', cat: 'complexity' },
  { name: 'space-complexity', cat: 'complexity' },
  { name: 'javascript', cat: 'language' },
  { name: 'python', cat: 'language' },
  { name: 'java', cat: 'language' },
  { name: 'c++', cat: 'language' },
];